# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}  
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  print_my_name:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo hello $MY_NAME
  
  # my_job:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - print_pipeline_id
  #     - run: exit 1
  #     - run:
  #         name: on error
  #         command: echo "Hello Error!"
  #         when: on_fail      
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - my_job
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_my_name      

